# -*- coding: utf-8 -*-
"""alone_final_progect.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bsWAZRPkHF40wQXWEYtYJd7Iw8V1_22A
"""

from google.colab import files
files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('cleaned_car_price.csv')

df.head()

df.info()

df.describe()

df.isin

print(df.isnull)

print(df.dropna(inplace=True))
print(df.isnull().sum())

df.columns

df.dtypes

#filter data by the year
data=df[(df['year']>=2015) & (df['year']<=2025)].reset_index()
data=data.drop(columns='index')
data

#sort data by the price
data_sorted=data.sort_values(by='price',ascending=False).reset_index(drop=True)
data_sorted

filter_data=data_sorted[(data_sorted['price']>10000)&(data_sorted['price']<30000)].reset_index(drop=True)
filter_data

filter_data.isnull().sum()

filter_data.shape

num_of_dublicate=filter_data.duplicated().sum()
print(num_of_dublicate)

# تحديد الفئات بناءً على حجم المحرك والمسافة المقطوعة
def classify_car(engine, mileage):
    if engine >= 3.0 &  mileage< 50000:
        return "Performance"  # سيارات قوية
    elif engine >= 1.5 &  mileage< 100000:
        return "Standard"  # سيارات متوسطة
    else:
        return "Economic"  # سيارات اقتصادية

# تطبيق الدالة على البيانات
df['model'] = df.apply(lambda row: classify_car(row['engineSize'], row['mileage']), axis=1)

# عرض أول 5 صفوف بعد التصنيف
print(df[['engineSize', 'mileage', 'model']].head())

#classifying data  by millege and enginesize
high_end=(filter_data['mileage']<5000)&(filter_data['engineSize']>=0.3)
standard=(filter_data['mileage']<10000)&(filter_data['engineSize']>=1.5)
low_end=(filter_data['mileage']<20000)&(filter_data['engineSize']>=2.5)
print(filter_data[['engineSize', 'mileage', 'model']].head())

print(filter_data[high_end].head())
print(filter_data[standard].head())
print(filter_data[low_end].head())

#visulation

#distribution of car brand
num_of_car= filter_data['brand'].value_counts()
figsize=(10,5)
filter_data['brand'].value_counts().plot(kind='bar')
plt.ylabel='number of car'
plt.xlabel='brand'
plt.title('distribution of car model')
plt.show()

#distribution of car brand
num_of_car= filter_data['model'].value_counts()
figsize=(5,20)
filter_data['model'].value_counts().plot(kind='bar')
plt.ylabel='number of car'
plt.xlabel='model'
plt.title('distribution of car ')
plt.show()

filter_data['transmission'].value_counts().plot(kind='pie',autopct='%1.1f%%',figsize=(5,5))
plt.title('transmission')
plt.show()

#diesel is the hieghest used
filter_data['fuelType'].value_counts().plot(kind='pie',autopct='%1.1f%%',figsize=(7,7),
                                            colors=plt.cm.Paired.colors, wedgeprops={'edgecolor': 'black'},
        textprops={'fontsize': 12})
plt.title('transmission')
plt.show()

filter_data['mileage'].dtypes
filter_data['mileage'] = pd.to_numeric(filter_data['mileage'], errors='coerce')
filter_data = filter_data.dropna(subset=['mileage'])

#mellige distribution
filter_data['mileage'].hist(bins=30,edgecolor='black',grid=False)
plt.title('#mellige distribution ')
#plt.xlabel('Mileage')
#plt.ylabel('frequency')

plt.show()

plt.figure(figsize=(15,6))
sns.heatmap(filter_data.pivot_table(index='engineSize', values='price', aggfunc='mean'), cmap='coolwarm', annot=True, fmt=".0f")

plt.title('engine size vs price')
plt.show()

#as the same in the previous
plt.figure(figsize=(15,6))
plt.hexbin(filter_data['engineSize'],filter_data['price'], cmap='coolwarm', mincnt=1,gridsize=30)
plt.colorbar(label=' car count ')

plt.title('engine size vs price')
plt.show()

#car engine vs mbg
sns.lineplot(data=filter_data,x='engineSize',y='mpg')
plt.title('engine size vs mbg')
plt.show()

#diference of the price over the year
plt.figure(figsize=(12,6))
sns.scatterplot(x=filter_data['year'],y=filter_data['price'],alpha=0.5,color='red')

plt.title('year vs price')

#diference of the price over the year by the line plot
plt.figure(figsize=(12,6))
sns.lineplot(x=filter_data['year'],y=filter_data['price'],errorbar=None)

plt.title('year vs price')

#diference of the price over the year
plt.figure(figsize=(12,6))
sns.scatterplot(x=filter_data['engineSize'],y=filter_data['mpg'],hue=filter_data['fuelType'],alpha=0.8)

plt.title('year vs price')

#diference of the price over brand
plt.figure(figsize=(12,6))
sns.scatterplot(x=filter_data['year'],y=filter_data['brand'],alpha=0.5,color='blue')

plt.title('year vs price')

#plineplot
#brand brice (السعر طبقا للعلامة التجارية)
#إذا كان شكل الكمان عريضًا → يوجد عدد كبير من السيارات في هذا النطاق السعري

#إذا كان هناك ذيل طويل للأعلى → هناك سيارات فاخرة غالية
 #  إذا كان هناك ذيل طويل للأسفل → هناك سيارات اقتصادية رخيصة.
#إذا كانت بعض الماركات لديها توزيع ضيق → أسعار سياراتها متقاربة.
plt.figure(figsize=(12,6))
sns.violinplot(data=filter_data,x='brand',y='price',inner='quartile')
plt.xticks(rotation=90)
plt.title('brand vs price')
plt.show()

plt.figure(figsize=(12,6))
sns.heatmap(filter_data.corr(numeric_only=True),annot=True,cmap='coolwarm',fmt=".2f")
plt.title('correlation')
plt.show()

